services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres' || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 3s
  app:
    container_name: app
    restart: always
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      bash -c "
        cd /app
        alembic upgrade head
        cd /app/src
        uvicorn app.main.main:app --host 0.0.0.0 --port 8000
      "
