name: setup
on:
  workflow_dispatch:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "main" ]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: get source
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run core ruff
        run: ruff check .

      - name: Run tests
        run: pytest -s -v
